---
- hosts: all
  tasks:
     - name: shutdown
       command: sudo /sbin/shutdown -h now
     - name: wait go down
       local_action: wait_for host={{ ansible_ssh_host }} port=22 state=stopped
